### PR TITLE
improve return type for detailedDiff

### PR DESCRIPTION
**Pull request by icholy**

### CODE REVIEW

**Comment by lucasprograms** [comment]
@mattphillips Thoughts on releasing / merging this change?

**Comment by willvedd** [comment]
This is a simple and impactful code change, would be great to see it get released!

**Comment by mattphillips** [comment]
Thanks @icholy

**Comment by mattphillips** [comment]
Released in https://www.npmjs.com/package/deep-object-diff/v/1.1.8

**Pull request merged**
